services:
  overometer:
    build: .
    container_name: overometer
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prismadb?schema=public
    depends_on:
      - db
    networks:
      - overometer

  overometer-db:
    image: postgres:13
    container_name: overometere-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - overometer

networks:
  overometer:

volumes:
  postgres-data:
